-- ============================================================================
-- PORRA MUNDIAL 2026 — Automated backups (×2/day) + tagged rollback
-- ----------------------------------------------------------------------------
-- Idempotent. Safe to run multiple times in the Supabase SQL editor.
--
-- WHAT THIS GIVES YOU
--   • A private `backups` schema that snapshots every app table as JSONB.
--   • backups.create_snapshot(tag, kind, note) → take a snapshot on demand.
--   • backups.restore_snapshot(tag, confirm) → tagged rollback to any snapshot
--     (always takes an automatic safety snapshot first, so a rollback is itself
--      undoable).
--   • backups.list_snapshots()  → see everything you have, newest first.
--   • backups.prune_snapshots() → retention: keeps recent auto snapshots + all
--     manual/pre-rollback ones.
--   • pg_cron jobs that snapshot twice a day and prune once a day.
--
-- SCOPE NOTE: this backs up the DATABASE tables only. It does NOT back up the
-- Storage `avatars` bucket (profile images). Those live in object storage; if
-- you want them versioned too, download the bucket separately before launch.
-- ============================================================================

-- ── 0. Extension (Supabase: also enable pg_cron under Database → Extensions) ──
create extension if not exists pg_cron;

-- ── 1. Schema + registry tables ──────────────────────────────────────────────
create schema if not exists backups;

create table if not exists backups.snapshots (
  id          bigint generated by default as identity primary key,
  tag         text unique not null,
  kind        text        not null default 'auto',  -- 'auto' | 'manual' | 'pre-rollback'
  created_at  timestamptz not null default now(),
  row_counts  jsonb,
  note        text
);

create table if not exists backups.snapshot_data (
  snapshot_id bigint not null references backups.snapshots(id) on delete cascade,
  table_name  text   not null,
  rows        jsonb  not null,                       -- the whole table as a json array
  primary key (snapshot_id, table_name)
);

-- The canonical list of app tables to protect, in FK-safe order
-- (parents first; children after). Used by both snapshot and restore.
create or replace function backups.app_tables()
returns text[] language sql immutable as $$
  select array[
    'users',
    'matches',
    'settings',
    'contact_messages',
    'predictions',
    'ko_predictions',
    'honours_predictions',
    'group_predictions',
    'scores'
  ]::text[];
$$;

-- ── 2. Create a snapshot ─────────────────────────────────────────────────────
create or replace function backups.create_snapshot(
  p_tag  text default null,
  p_kind text default 'manual',
  p_note text default null
) returns text
language plpgsql
security definer
set search_path = backups, public
as $$
declare
  v_tag   text := coalesce(p_tag, to_char(now() at time zone 'utc','YYYYMMDD_HH24MI"Z"'));
  v_id    bigint;
  v_tbl   text;
  v_rows  jsonb;
  v_count int;
  v_counts jsonb := '{}'::jsonb;
begin
  -- Make the tag unique if one already exists with the same name
  if exists (select 1 from backups.snapshots where tag = v_tag) then
    v_tag := v_tag || '_' || substr(md5(random()::text), 1, 4);
  end if;

  insert into backups.snapshots(tag, kind, note)
  values (v_tag, coalesce(p_kind,'manual'), p_note)
  returning id into v_id;

  foreach v_tbl in array backups.app_tables() loop
    execute format(
      'select coalesce(jsonb_agg(to_jsonb(t)), ''[]''::jsonb), count(*) from public.%I t',
      v_tbl
    ) into v_rows, v_count;

    insert into backups.snapshot_data(snapshot_id, table_name, rows)
    values (v_id, v_tbl, v_rows);

    v_counts := v_counts || jsonb_build_object(v_tbl, v_count);
  end loop;

  update backups.snapshots set row_counts = v_counts where id = v_id;
  return v_tag;
end;
$$;

-- ── 3. Tagged rollback ───────────────────────────────────────────────────────
-- Restores every app table to the state captured in snapshot <p_tag>.
-- Requires p_confirm => true to actually run (guards against accidents).
-- Always takes a 'pre-rollback' safety snapshot first, so you can undo a rollback.
create or replace function backups.restore_snapshot(
  p_tag     text,
  p_confirm boolean default false
) returns text
language plpgsql
security definer
set search_path = backups, public
as $$
declare
  v_id      bigint;
  v_tbl     text;
  v_rows    jsonb;
  v_safety  text;
  v_list    text;
begin
  if not p_confirm then
    raise exception
      'Refusing to roll back: call backups.restore_snapshot(%, true) to confirm.', quote_literal(p_tag);
  end if;

  select id into v_id from backups.snapshots where tag = p_tag;
  if v_id is null then
    raise exception 'No snapshot found with tag %', quote_literal(p_tag);
  end if;

  -- Safety snapshot of the CURRENT state before we overwrite anything.
  v_safety := backups.create_snapshot(
    'pre-rollback_' || to_char(now() at time zone 'utc','YYYYMMDD_HH24MI"Z"'),
    'pre-rollback',
    'Auto-taken before rolling back to ' || p_tag
  );

  -- Wipe all app tables at once. A single multi-table TRUNCATE handles the
  -- foreign keys between them; CASCADE covers any dependent rows; RESTART
  -- IDENTITY zeroes the sequences (we re-sync them after the reload).
  select string_agg(format('public.%I', t), ', ')
  into v_list
  from unnest(backups.app_tables()) as t;
  execute 'truncate table ' || v_list || ' restart identity cascade';

  -- Reload parents → children (app_tables order) so FKs are satisfied as we go.
  foreach v_tbl in array backups.app_tables() loop
    select rows into v_rows
    from backups.snapshot_data
    where snapshot_id = v_id and table_name = v_tbl;

    if v_rows is not null and jsonb_array_length(v_rows) > 0 then
      execute format(
        'insert into public.%I select * from jsonb_populate_recordset(null::public.%I, $1)',
        v_tbl, v_tbl
      ) using v_rows;
    end if;
  end loop;

  -- Re-sync identity sequences so future inserts don't collide with restored ids.
  perform backups.resync_identity_sequences();

  return format('Rolled back to snapshot "%s". Safety snapshot of prior state saved as "%s".',
                p_tag, v_safety);
end;
$$;

-- Helper: fix identity sequences after a restore (predictions.id, ko_predictions.id, ...)
create or replace function backups.resync_identity_sequences()
returns void
language plpgsql
security definer
set search_path = backups, public
as $$
declare
  r record;
begin
  for r in
    select c.relname as tbl, a.attname as col,
           pg_get_serial_sequence('public.'||c.relname, a.attname) as seq
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
    where n.nspname = 'public'
      and c.relkind = 'r'
      and c.relname = any (backups.app_tables())
      and pg_get_serial_sequence('public.'||c.relname, a.attname) is not null
  loop
    execute format(
      'select setval(%L, coalesce((select max(%I) from public.%I), 0) + 1, false)',
      r.seq, r.col, r.tbl
    );
  end loop;
end;
$$;

-- ── 4. Convenience: list + prune ─────────────────────────────────────────────
create or replace function backups.list_snapshots()
returns table(tag text, kind text, created_at timestamptz, row_counts jsonb, note text)
language sql stable as $$
  select tag, kind, created_at, row_counts, note
  from backups.snapshots
  order by created_at desc;
$$;

-- Retention: keep the most recent N auto snapshots; keep ALL manual + pre-rollback.
create or replace function backups.prune_snapshots(p_keep_auto int default 14)
returns int
language plpgsql
security definer
set search_path = backups, public
as $$
declare v_deleted int;
begin
  with ranked as (
    select id,
           row_number() over (order by created_at desc) as rn
    from backups.snapshots
    where kind = 'auto'
  )
  delete from backups.snapshots s
  using ranked r
  where s.id = r.id and r.rn > p_keep_auto;
  get diagnostics v_deleted = row_count;
  return v_deleted;   -- snapshot_data rows cascade-delete automatically
end;
$$;

-- ── 5. Schedule with pg_cron ─────────────────────────────────────────────────
-- pg_cron runs on UTC. Your site is unified to US Eastern; the two times below
-- are ~03:00 and ~15:00 Eastern (07:00 / 19:00 UTC). Adjust if you prefer.
-- Unschedule any prior versions first so re-running this file stays idempotent.
do $$
declare j text;
begin
  foreach j in array array['porra_backup_am','porra_backup_pm','porra_backup_prune'] loop
    if exists (select 1 from cron.job where jobname = j) then
      perform cron.unschedule(j);
    end if;
  end loop;
end $$;

select cron.schedule('porra_backup_am', '0 7 * * *',
  $$select backups.create_snapshot(null, 'auto', 'Scheduled AM backup');$$);

select cron.schedule('porra_backup_pm', '0 19 * * *',
  $$select backups.create_snapshot(null, 'auto', 'Scheduled PM backup');$$);

select cron.schedule('porra_backup_prune', '30 7 * * *',
  $$select backups.prune_snapshots(14);$$);

-- ── 6. Take one snapshot right now so you start with a baseline ───────────────
select backups.create_snapshot('baseline_launch', 'manual', 'First snapshot at install time');

-- ============================================================================
-- HOW TO USE
--   • See what you have:
--       select * from backups.list_snapshots();
--   • Manual snapshot before a risky change:
--       select backups.create_snapshot('before_lock_test', 'manual', 'testing lock');
--   • Roll back to a tag (must confirm with true):
--       select backups.restore_snapshot('before_lock_test', true);
--     A 'pre-rollback_*' snapshot of the current state is saved automatically,
--     so you can undo the rollback by restoring that tag.
--   • Check scheduled jobs:
--       select jobname, schedule, active from cron.job where jobname like 'porra_%';
-- ============================================================================
