-- ============================================================================
-- PORRA MUNDIAL 2026 — Supabase setup (complete & idempotent)
-- ----------------------------------------------------------------------------
-- Safe to run multiple times. Rebuilds the entire database from scratch if you
-- ever recreate the project. Reflects the live schema as of the launch build.
--
-- NOTE ON SECURITY: Row Level Security (RLS) is intentionally DISABLED on the
-- app tables for this private friends-only pool, so the anon key can read/write
-- directly from the static site. If you ever make the pool public, revisit this.
-- ============================================================================

-- ── USERS ───────────────────────────────────────────────────────────────────
create table if not exists public.users (
  id            uuid primary key references auth.users(id) on delete cascade,
  email         text unique,
  first_name    text,
  last_name     text,
  alias         text,
  country       text,
  phone         text,
  payment_status text default 'pending',   -- 'pending' | 'active'
  is_admin      boolean default false,
  blocked       boolean default false,
  avatar_url    text,
  created_at    timestamptz default now()
);
-- add-if-missing (for older projects)
do $$ begin
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='users' and column_name='blocked')     then alter table public.users add column blocked boolean default false; end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='users' and column_name='avatar_url')  then alter table public.users add column avatar_url text; end if;
end $$;
alter table public.users disable row level security;

-- ── MATCHES (group stage + knockouts) ────────────────────────────────────────
create table if not exists public.matches (
  id            text primary key,         -- e.g. 'M1' … 'M104'
  phase         text,                     -- 'group' | 'r32' | 'r16' | 'qf' | 'sf' | 'final'
  group_letter  text,                     -- 'A'..'L' for group games
  home_team     text,
  away_team     text,
  home_flag     text,                     -- flagcdn code, e.g. 'es'
  away_flag     text,
  kickoff       timestamptz,
  venue         text,
  city          text,
  real_home     int,                      -- actual result (null until played)
  real_away     int,
  bonus         int default 1,
  result_locked boolean default false
);
alter table public.matches disable row level security;

-- ── PREDICTIONS (group + knockout match scores) ──────────────────────────────
create table if not exists public.predictions (
  id            bigint generated by default as identity primary key,
  user_id       uuid references public.users(id) on delete cascade,
  match_id      text references public.matches(id) on delete cascade,
  predicted_home int,
  predicted_away int,
  submitted_at  timestamptz default now()
);
do $$ begin
  if not exists (select 1 from pg_constraint where conname='predictions_user_match_uniq') then
    alter table public.predictions add constraint predictions_user_match_uniq unique (user_id, match_id);
  end if;
end $$;
alter table public.predictions disable row level security;

-- ── KO_PREDICTIONS (bracket: advancer + score per slot) ───────────────────────
create table if not exists public.ko_predictions (
  id            bigint generated by default as identity primary key,
  user_id       uuid references public.users(id) on delete cascade,
  slot_id       text,                     -- e.g. 'r32_0' … 'final_0'
  home_team     text,
  away_team     text,
  pred_home     int,
  pred_away     int,
  advanced      text,                     -- team the user picked to advance
  submitted_at  timestamptz default now()
);
do $$ begin
  if not exists (select 1 from pg_constraint where conname='ko_predictions_user_slot_uniq') then
    alter table public.ko_predictions add constraint ko_predictions_user_slot_uniq unique (user_id, slot_id);
  end if;
end $$;
alter table public.ko_predictions disable row level security;

-- ── HONOURS_PREDICTIONS (Bota / Balón, etc.) ──────────────────────────────────
create table if not exists public.honours_predictions (
  user_id    uuid primary key references public.users(id) on delete cascade,
  boot_1     text, boot_2 text, boot_3 text,   -- Bota de Oro picks
  ball_1     text, ball_2 text, ball_3 text,   -- Balón de Oro picks
  surprise   text,
  revelation text
);
alter table public.honours_predictions disable row level security;

-- ── GROUP_PREDICTIONS (reserved; currently unused by the UI) ──────────────────
create table if not exists public.group_predictions (
  id       bigint generated by default as identity primary key,
  user_id  uuid references public.users(id) on delete cascade,
  group_letter text,
  pos_1 text, pos_2 text, pos_3 text, pos_4 text
);
alter table public.group_predictions disable row level security;

-- ── SCORES (computed by the scoring engine) ───────────────────────────────────
create table if not exists public.scores (
  user_id         uuid primary key references public.users(id) on delete cascade,
  total           int default 0,
  group_match_pts int default 0,
  standings_pts   int default 0,
  r32_pts         int default 0,
  r16_pts         int default 0,
  qf_pts          int default 0,
  sf_pts          int default 0,
  final_pts       int default 0,
  honours_pts     int default 0,
  exact_scores    int default 0,
  rank            int,
  updated_at      timestamptz default now()
);
alter table public.scores disable row level security;

-- ── SETTINGS (key/value config read by the site) ─────────────────────────────
create table if not exists public.settings (
  key   text primary key,
  value text
);
alter table public.settings disable row level security;

insert into public.settings (key, value) values
  ('entry_fee',          '20'),
  ('predictions_locked', 'false'),
  ('tournament_started', 'false'),
  ('paypal_handle',      ''),
  ('venmo_handle',       '@juanft'),
  ('zelle_contact',      ''),
  ('whatsapp_link',      '')
on conflict (key) do nothing;

-- ── CONTACT_MESSAGES (contact form inbox) ─────────────────────────────────────
create table if not exists public.contact_messages (
  id         uuid primary key default gen_random_uuid(),
  name       text,
  email      text,
  message    text not null,
  created_at timestamptz default now(),
  resolved   boolean default false
);
alter table public.contact_messages disable row level security;

-- ── STORAGE: avatars bucket (public) + upload/read policies ───────────────────
-- Create the bucket if it doesn't exist (public read).
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do update set public = true;

-- Allow anyone to upload / update / read in the public avatars bucket.
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and policyname='avatars public upload') then
    create policy "avatars public upload" on storage.objects for insert with check (bucket_id = 'avatars');
  end if;
  if not exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and policyname='avatars public update') then
    create policy "avatars public update" on storage.objects for update using (bucket_id = 'avatars');
  end if;
  if not exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and policyname='avatars public read') then
    create policy "avatars public read" on storage.objects for select using (bucket_id = 'avatars');
  end if;
end $$;

-- ============================================================================
-- AFTER RUNNING THIS:
--   • Authentication → URL Configuration:
--       Site URL      = https://porradelmundial.com
--       Redirect URLs = https://porradelmundial.com/porra-login.html
--   • Load match fixtures into public.matches (id, phase, teams, kickoff, …).
--   • Mark an admin:  update public.users set is_admin = true where email = 'you@example.com';
-- ============================================================================


-- ── Late additions (idempotent; safe to re-run) ──
alter table users  add column if not exists seen_payment_confirm boolean default false;
alter table scores add column if not exists prev_rank int;
insert into settings (key, value) values
  ('maintenance_mode','false'), ('real_bota',''), ('real_balon',''),
  ('currency','EUR'), ('hide_picks','false'), ('maint_banner','false'), ('maint_banner_time',''),
  ('real_champion',''), ('real_runnerup','')
on conflict (key) do nothing;
